services:
  app:
    build: .
    container_name: inventori-msu-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    env_file:
      - .env.docker
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: inventori-msu-web
    restart: unless-stopped
    ports:
      - "8080:80"          # akses: http://localhost:8080
    volumes:
      - ./:/var/www        # serve kode yang sama
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: inventori-msu-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventori_msu
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"        # supaya tidak bentrok dengan MySQL lokal
    volumes:
      - dbdata:/var/lib/mysql

  vite:
    image: node:20
    container_name: inventori-msu-vite
    working_dir: /var/www
    command: sh -c "npm i && npx vite --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    depends_on:
      - app

volumes:
  dbdata:
